INSERT INTO ferramentas (nome_ferramenta, descricao_ferramenta) VALUES
('Chave de fenda', 'Usada para apertar ou soltar parafusos de fenda simples.'),
('Chave Philips', 'Chave com ponta em cruz, usada em diversos equipamentos.'),
('Chave Allen', 'Chave em formato hexagonal, ideal para montagens de precisão.'),
('Alicate universal', 'Ferramenta multiuso para segurar, cortar ou entortar fios.'),
('Alicate de corte', 'Utilizado para cortes precisos de fios ou materiais plásticos.'),
('Furadeira', 'Ferramenta elétrica para furar superfícies variadas.'),
('Parafusadeira', 'Aparafusa ou desaparafusa com torque automático.'),
('Multímetro', 'Instrumento para medir tensão, corrente e resistência.'),
('Estilete', 'Ferramenta de corte manual precisa, ideal para papel e plásticos.'),
('Serra tico-tico', 'Serra elétrica portátil para cortes em madeira ou MDF.'),
('Tesoura', 'Ferramenta comum de corte para papel, tecidos e fitas.'),
('Martelo', 'Ferramenta de impacto para pregos e montagens simples.'),
('Impressora 3D', 'Impressora que fabrica objetos camada por camada.'),
('Scanner 3D', 'Equipamento para digitalizar objetos reais em 3D.'),
('Estação de solda', 'Unidade que inclui ferro de solda com controle de temperatura.'),
('Ferro de solda', 'Ferramenta básica para soldar componentes eletrônicos.'),
('Pinça de precisão', 'Usada para manusear pequenos componentes com precisão.'),
('Micro retífica', 'Ferramenta rotativa para lixar, furar ou polir com precisão.'),
('Osciloscópio', 'Equipamento de diagnóstico para analisar sinais elétricos.'),
('Placa Arduino', 'Placa de prototipagem eletrônica muito utilizada em projetos.'),
('Placa Raspberry Pi', 'Mini computador usado em automação, robótica e prototipagem.'),
('Fonte de bancada', 'Fonte com ajuste de tensão e corrente para testes e protótipos.'),
('Ventosa de vácuo', 'Dispositivo para levantar objetos por vácuo, útil em protótipos sensíveis.'),
('Espátula cirúrgica', 'Utilizada para manipulação ou modelagem de materiais moles.'),
('Estetoscópio', 'Dispositivo usado para auscultar sons do corpo humano.'),
('Esfigmomanômetro', 'Equipamento de medição de pressão arterial.'),
('Eletroestimulador', 'Aparelho para fisioterapia de estimulação muscular.'),
('Halteres de fisioterapia', 'Pesos leves utilizados em reabilitação física.'),
('Bola terapêutica', 'Bola inflável usada para exercícios motores e sensoriais.'),
('Faixa elástica de resistência', 'Faixa elástica usada em exercícios de resistência progressiva.'),
('Kit de motricidade fina', 'Conjunto de objetos para desenvolver coordenação motora fina.'),
('Balança digital', 'Balança precisa para medir massa corporal ou objetos leves.'),
('Cadeira ergonômica', 'Cadeira projetada para conforto e postura durante o uso prolongado.'),
('Andador articulado', 'Auxílio de locomoção articulado para mobilidade e reabilitação.'),
('Bengala tripé', 'Bengala com base tripla, mais estável que modelos comuns.'),
('Otoscópio', 'Instrumento médico usado para observar o interior do ouvido.'),
('Lupa de aumento', 'Lente de aumento usada para leitura ou inspeção de pequenos objetos.'),
('Lanterna clínica', 'Iluminação portátil para inspeção médica ou técnica.');



-- MATERIAIS
INSERT INTO materiais (nome_material, descricao_material) VALUES
('PLA', 'Filamento biodegradável amplamente utilizado na impressão 3D, ideal para prototipagem.'),
('ABS', 'Filamento resistente e durável, utilizado em peças funcionais impressas em 3D.'),
('Filamento PETG', 'Filamento flexível e resistente à umidade para impressoras 3D.'),
('MDF 3mm', 'Chapa de madeira densa, ideal para corte a laser e estrutura de protótipos.'),
('MDF 6mm', 'Versão mais espessa do MDF, proporciona maior rigidez.'),
('Acrílico 3mm', 'Material plástico transparente, utilizado em proteções e carcaças.'),
('Acrílico 5mm', 'Mais resistente, usado em estruturas maiores ou bases.'),
('Papelão', 'Material leve e reciclável, ótimo para mockups e maquetes.'),
('PVC expandido', 'Plástico leve, utilizado em placas, sinalizações e artesanato técnico.'),
('Espuma EVA', 'Espuma densa utilizada em apoio, enchimentos ou ergonomia.'),
('Velcro', 'Sistema de fixação reutilizável muito usado em dispositivos adaptáveis.'),
('Fita dupla face', 'Fita adesiva de alta aderência, utilizada em fixações temporárias ou estruturais leves.'),
('Fita crepe', 'Fita adesiva leve para marcações ou protetores temporários.'),
('Parafuso M3', 'Parafuso fino e versátil, utilizado em eletrônicos e estruturas pequenas.'),
('Parafuso M4', 'Mais robusto, ideal para montagem de estruturas.'),
('Porca M3', 'Utilizada para fixação de parafusos M3.'),
('Porca M4', 'Porca compatível com parafusos M4 para montagem sólida.'),
('Arruela M3', 'Distribui pressão em conexões com parafusos.'),
('Madeira balsa', 'Madeira leve e fácil de cortar, ideal para protótipos e miniaturas.'),
('Barra de alumínio', 'Material metálico resistente para reforço estrutural.'),
('Fita isolante', 'Fita utilizada para isolamento de conexões elétricas.'),
('Fita térmica', 'Usada para dissipação térmica em componentes eletrônicos.'),
('Sensor de pressão', 'Dispositivo sensível usado em superfícies de pressão.'),
('Sensor de temperatura', 'Detecta variações de temperatura em tempo real.'),
('Sensor de movimento', 'Sensor para detectar movimento em ambientes ou dispositivos.'),
('Módulo Bluetooth', 'Módulo para comunicação sem fio entre dispositivos.'),
('Display LCD 16x2', 'Display de 2 linhas usado em projetos Arduino para exibir informações.'),
('Resistores', 'Componentes básicos de circuitos eletrônicos.'),
('Capacitores', 'Armazenam energia temporariamente em circuitos.'),
('Protoboard', 'Base reutilizável para montagem de circuitos eletrônicos sem solda.'),
('Fios jumper', 'Cabos de conexão flexíveis para protoboards e módulos.'),
('Led 5mm', 'LEDs de 5mm com diversas cores para sinalização visual.'),
('Bateria 9V', 'Fonte portátil de alimentação para circuitos e motores.'),
('Motor DC 6V', 'Motor básico de corrente contínua para robótica e eletrônica.'),
('Servo motor SG90', 'Servo motor popular em automação, controle de movimento e robôs.'),
('Placa de acrílico', 'Chapa transparente ou colorida para estrutura ou acabamento.'),
('Cola quente', 'Adesivo termofusível prático e resistente, muito usado em protótipos rápidos.'),
('Cola de contato', 'Cola forte e flexível, usada em tecidos, borracha e plásticos.'),
('Cola epóxi', 'Cola de dois componentes, ideal para fixações estruturais permanentes.'),
('Tinta acrílica', 'Utilizada para acabamento de projetos e decoração visual.'),
('Tinta spray', 'Spray de pintura para acabamento rápido e uniforme.'),
('Tecido resistente', 'Tecido resistente usado em suportes, cintas e bolsas terapêuticas.'),
('Elástico cirúrgico', 'Utilizado em máscaras e projetos médicos, resistente e flexível.'),
('Borracha EVA 10mm', 'Material espesso e confortável para apoio ou bases de estrutura.'),
('Imã de neodímio', 'Imã super potente usado em sistemas de encaixe ou sensores.');
